CREATE DATABASE IF NOT EXISTS infodba;
USE infodba;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    cateogry VARCHAR(20) NOT NULL,
    H_Pass VARCHAR(255) NOT NULL,
    S_pass VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS auser(
   id INT AUTO_INCREMENT PRIMARY KEY,
   username VARCHAR(50) NOT NULL,
   s_key VARCHAR(255) NOT NULL,
   email VARCHAR(100) NOT NULL
);